<div class="section section-header">
    <div class="parallax pattern-image">
        <img src="http://www.annapipoyan.com/images/bolly7.jpg"/>
<!--                     <img src="/assets/img/header6.jpg"/> -->
        <div class="container">
            <div class="content">
                <h1>Shakti</h1>
                <div class="separator-container">
                    <div class="separator line-separator">∎</div>
                </div>
                <h5>EMPOWERMENT OF WOMEN, CHILDREN AND FAMILIES SOCIETY</h5>
            </div>
        </div>
    </div>
    <a href="" data-scroll="true" data-id="#whoWeAre" class="scroll-arrow hidden-xs hidden-sm">
    <i class="fa fa-angle-down"></i>
    </a>
</div>
<div class="section section-we-are-1" id="whoWeAre">
    <div class="text-area">
        <div class="container">
            <div class="row">
                <div class="title" id="animationTest">
                    <h2>Who we are</h2>
                    <div class="separator-container">
                        <div class="separator line-separator">∎</div>
                    </div>
                    <p class="large">
                      This is a non-profit society dedicated to empowering individuals, families and communities. Our vision is to inspire, motivate and create vibrant communities by utilizing and enhancing the social capital of our citizens. We are committed to working with underprivileged members of our community and bringing resources together to support those in need.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section section-we-do-2" id="workflow">
    <div class="container">
        <div class="row">
            <div class="title add-animation">
                <h2>What we do</h2>
                <div class="separator-container">
                    <div class="separator line-separator">∎</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="card add-animation animation-1">
                    <div class="icon">
                        <i class="pe-7s-tools"></i>
                    </div>
                    <h3>Make Aware</h3>
                    <p>To create awareness around current issues impacting women, children and families through media and public forums.</p>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card add-animation animation-2">
                    <div class="icon">
                        <i class="pe-7s-gift"></i>
                    </div>
                    <h3>collaborate</h3>
                    <p>
                    To collaborate with similar societies and initiatives in Canada to enhance services available to women, children and families</p>
                </div>
            </div>
        </div>
    </div>
</div>
<? /*
<div class="section section-clients-2" id="clients">
    <div class="container">
        <div class="title add-animation">
            <h2>What people think...</h2>
            <div class="separator-container">
                <div class="separator line-separator">∎</div>
            </div>
        </div>
        <div class="tab-content quotes add-animation animation-2">
            <div class="tab-pane active" id="sony">
                <p class="large">Hello there, My Name is Abhi Khatri. You're simply awesome. I would love to contact you. Everytime I checkout your stuff it gives me idea to make my own stuff. Keep it up :)</p>
            </div>

            <div class="tab-pane" id="canon">
                <p class="large">Hello there, My Name is Abhi Khatri. You're simply awesome. I would love to contact you. Everytime I checkout your stuff it gives me idea to make my own stuff. Keep it up :)</p>
            </div>

            <div class="tab-pane" id="samsung">
                <p class="large">Hello there, My Name is Abhi Khatri. You're simply awesome. I would love to contact you. Everytime I checkout your stuff it gives me idea to make my own stuff. Keep it up :)</p>
            </div>

            <div class="tab-pane" id="intel">
                <p class="large">Hello there, My Name is Abhi Khatri. You're simply awesome. I would love to contact you. Everytime I checkout your stuff it gives me idea to make my own stuff. Keep it up :)</p>
            </div>
        </div>
        <ul class="nav nav-text list-logos add-animation animation-2" role="tablist">
            <li class="active">
                <a href="../#sony" role="tab" data-toggle="tab">
                    <h3 class="big-text">Anubir Singh</h3>
                </a>
            </li>
            <li>
                <a href="../#canon" role="tab" data-toggle="tab">
                    <h3 class="big-text">Sonia Andhi</h3>
                </a>
            </li>
            <li>
                <a href="../#samsung" role="tab" data-toggle="tab">
                    <h3 class="big-text">Fars Kid</h3>
                </a>
            </li>
            <li>
                <a href="../#intel" role="tab" data-toggle="tab">
                    <h3 class="big-text">Sameer Bilku</h3>
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="section section-team-2" id="team">
    <div class="container">
        <div class="text-area">
            <div class="title add-animation">
                <h2>Meet our Team</h2>
                <div class="separator-container">
                    <div class="separator line-separator">∎</div>
                </div>

            </div>
        </div>
        <div class="team">
            <div class="row">
                <div class="col-md-3">
                    <div class="member add-animation animation-1">
                        <img class="img-circle" src="assets/img/elena.jpg"/>
                        <div class="description">
                            <h3 class="big-text">Elena Conacel </h3>
                            <br>
                            <p class="small-text">Elena is one of the co-founders and takes care of growth, product development and partnerships. She is analytical, driven and adapts easily to new conditions, while trying to keep everyone on track.
                            </p>
                        </div>
                        <div class="social-buttons hidden-xs">
                           <a target="_blank" href="https://twitter.com/conacelelena" class="btn btn-social btn-twitter btn-simple"><i class="fa fa-twitter"></i></a>
                            <a target="_blank" href="https://www.linkedin.com/in/elena-cristina-conacel-a89a436b" class="btn btn-social btn-linkedin btn-simple"><i class="fa fa-linkedin-square"></i></a>                                    </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="member add-animation animation-2">
                        <img class="img-circle" src="assets/img/diana.png"/>
                        <div class="description">
                            <h3 class="big-text">Diana Caliman </h3>
                            <br>
                            <p class="small-text">Diana is the person behind our social media channels, she takes care of our users' community and communication. She is ambitious, hard-working, instantly likeable and fun to be around.
                            </p>
                        </div>
                        <div class="social-buttons hidden-xs">
                            <a target="_blank" href="https://twitter.com/eDianaCaliman" class="btn btn-social btn-twitter btn-simple"><i class="fa fa-twitter"></i></a>
                             <a target="_blank" href="https://www.linkedin.com/in/diana-caliman-751552b5" class="btn btn-social btn-linkedin btn-simple"><i class="fa fa-linkedin-square"></i></a>
                             <a target="_blank" href="https://www.facebook.com/DianaaCaliman?fref=ts" class="btn btn-social btn-facebook btn-simple"><i class="fa fa-facebook-square"></i></a>
                        </div>


                    </div>
                </div>
                <div class="col-md-3">
                    <div class="member add-animation animation-3">
                        <img class="img-circle" src="assets/img/alex.png"/>
                        <div class="description">
                            <h3 class="big-text">Alex Paduraru</h3>
                            <br>
                            <p class="small-text">Alex is one of the co-founders and drives the technical strategy of the platform, customer support and brand. He is level-headed, smart and with a taste for simple, aesthetic design.</p>
                        </div>
                        <div class="social-buttons hidden-xs">
                            <a target="_blank" href="https://www.facebook.com/axelut?fref=ts" class="btn btn-social btn-facebook btn-simple"><i class="fa fa-facebook-square"></i></a>
                            <a target="_blank" href="https://twitter.com/Axelut" class="btn btn-social btn-twitter btn-simple"><i class="fa fa-twitter"></i></a>
                            <a target="_blank" href="https://www.linkedin.com/in/alexpaduraru" class="btn btn-social btn-linkedin btn-simple"><i class="fa fa-linkedin-square"></i></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="member add-animation animation-4">
                        <img class="img-circle" src="assets/img/beni.jpg"/>
                        <div class="description">
                            <h3 class="big-text">Beniamin Marcu</h3>
                            <br>
                            <p class="small-text">Beni is the guy responsible for keeping the platform in check, improving its functionality and adding new features. He is driven, always open for learning more, friendly and a fan of Ruby on Rails.
                            </p>
                        </div>

                        <div class="social-buttons hidden-xs">
                           <a target="_blank" href="https://twitter.com/marcu_beniamin" class="btn btn-social btn-twitter btn-simple"><i class="fa fa-twitter"></i></a>
                            <a target="_blank" href="https://www.linkedin.com/in/beniamin-marcu-52856947" class="btn btn-social btn-linkedin btn-simple"><i class="fa fa-linkedin-square"></i></a>
                            <a target="_blank" href="https://www.facebook.com/beniamin.marcu.1?fref=ts" class="btn btn-social btn-facebook btn-simple"><i class="fa fa-facebook-square"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
*/?>
<div class="section section-numbers-1" id="numbers">
    <div class="container">
      <div class="col-md-8 col-md-push-2">
        <div class="clearfix"></div>
        <div class="row">
            <div class="col-md-4 col-sm-4">
                <div class="card card-plain add-animation animation-1">
                    <h4>Address</h4>
                    <div class="separator-container">
                        <div class="separator line-separator">∎</div>
                    </div>
                    <h5>Vancouver, BC</h5>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="card card-plain add-animation animation-2">
                  <h4>Phone</h4>
                  <div class="separator-container">
                      <div class="separator line-separator">∎</div>
                  </div>
                  <h5>(604) 307-8796</h5>
                </div>
            </div>
            <div class="col-md-4 col-sm-4">
                <div class="card card-plain add-animation animation-3">
                  <h4>Email</h4>
                  <div class="separator-container">
                      <div class="separator line-separator">∎</div>
                  </div>
                  <h5><a href="mailto:info@shaktisociety.com">info@shaktisociety.com</a></h5>
                </div>
            </div>
        </div>
      </div>
    </div>
</div>
