  <div class="inner cover">
    <img src="<?=_RES_;?>img/logo.png" width="400">
    <h1 class="cover-heading">Scouty.io</h1>
    <p class="lead">The future of something amazing.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-default">Learn more</a>
    </p>
  </div>

  <div class="mastfoot">
    <div class="inner">
      <p>Copyright &copy; <a href="http://scouty.io">Scouty</a></p>
    </div>
  </div>