  <div class="inner cover">
    <img src="<?=_RES_;?>img/logo.png" width="400">
    <h1 class="cover-heading">Scouty.io</h1>
    <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
    <p class="lead">
      <a href="#" class="btn btn-lg btn-default">Learn more</a>
    </p>
  </div>

  <div class="mastfoot">
    <div class="inner">
      <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
    </div>
  </div>